# Generated by Django 5.0.7 on 2024-07-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0003_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(),
        ),
    ]
